# Site settings
title:          eypidan's blog
description:    "Minimal Jekyll theme for storytellers"
baseurl:
url:            "https://eypidan.github.io"


# Author
author:
  name:         eypidan
  url:          https://chester.how
  email:        eypidanh@gmail.com

# Google Analytics
google_analytics: UA-144242599-1

# Build settings
markdown:       kramdown


# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

